language: node_js

node_js:
  - "14.16.0"

services: docker

jobs:
  include:
    - stage: Docker image build
      before_install:
        - docker build -t spacekatt/spacekatt-io:latest .
      script: echo 'Docker build successful'
    - stage: Minesweeper tests
      before_install:
        - echo 'Checking for missing change logs...' && echo -en 'travis_fold:start:change\\r'
        - git fetch origin main:refs/remotes/origin/main -a
        - node common/scripts/install-run-rush.js change -v
        - echo -en 'travis_fold:end:change\\r'

      install:
        - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
        - node common/scripts/install-run-rush.js install
        - echo -en 'travis_fold:end:install\\r'

      script:
        - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
        - node common/scripts/install-run-rush.js rebuild --verbose
        - echo -en 'travis_fold:end:build\\r'

        - echo 'Run Minesweeper tests'
        - cd apps/Minesweeper
        - heft test
