jobs:
  include:
    - stage: Docker image build
      language: minimal
      services: docker
      script:
        - echo 'Building Docker image to serve content with NGINX...' && echo -en 'travis_fold:start:dockerbuild\\r'
        - set -e
        - docker build -t spacekatt/spacekatt-io:latest .
        - echo -en 'travis_fold:end:dockerbuild\\r'
        - echo 'Docker build successful'

    - stage: rush build && heft test
      language: node_js
      node_js:
        - "14.16.0"
      script:
        - set -e

        - echo 'Checking for missing change logs...' && echo -en 'travis_fold:start:change\\r'
        - git fetch origin main:refs/remotes/origin/main -a
        - node common/scripts/install-run-rush.js change -v
        - echo -en 'travis_fold:end:change\\r'

        - echo 'Installing build toolchain...' && echo -en 'travis_fold:start:install\\r'
        - node common/scripts/install-run-rush.js install
        - npm install --global @rushstack/heft
        - echo -en 'travis_fold:end:install\\r'

        - echo 'Building projects in monorepo...' && echo -en 'travis_fold:start:build\\r'
        - node common/scripts/install-run-rush.js rebuild --verbose
        - echo -en 'travis_fold:end:build\\r'

        - echo 'Testing Minesweeper...' && echo -en 'travis_fold:start:testminesweeper\\r'
        - cd apps/minesweeper
        - heft test
        - cd ../..
        - echo -en 'travis_fold:end:testminesweeper\\r'

        - echo 'All application tests run successfully'
