name: Build and Deploy Website

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write

env:
  ARTIFACT_NAME: 'website-artifact'
  BUILD_DIRECTORY: './spacekatt-io/build/'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    # Setup
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install build toolchain
      run: |
        node common/scripts/install-run-rush.js install
        npm install --global @rushstack/heft

    # Build
    - name: Build projects in monorepo
      run: node common/scripts/install-run-rush.js rebuild --verbose

    # Test
    - name: Test Minesweeper
      working-directory: ./apps/minesweeper
      run: heft test --no-build

    - name: Publish Website Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: '${{ env.BUILD_DIRECTORY }}'

  deploy-website:
    runs-on: ubuntu-latest

    needs: build-and-publish
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.BUILD_DIRECTORY }}

    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Deploy website to GCP
      run: 'gsutil -m rsync -R -d -c build/ gs://${{ secrets.GCP_BUCKET_NAME }}'
