name: Build and Deploy Website

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main

env:
  ARTIFACT_NAME: 'website-artifact'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Check for missing change logs
      #   run: |
      #     git fetch origin main:refs/remotes/origin/main -a
      #     node common/scripts/install-run-rush.js change -v
      - name: Install build toolchain
        run: |
          node common/scripts/install-run-rush.js install
          npm install --global @rushstack/heft

      # Build
      - name: Build projects in monorepo
        run: node common/scripts/install-run-rush.js rebuild --verbose

      # Test
      - name: Test Minesweeper
        working-directory: ./apps/minesweeper
        run: heft test --no-build

      - name: Publish Website Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: './spacekatt-io/build/'

